#!/usr/bin/env php
<?php

require(__DIR__."/../common.php");

// Just pass the data to the local receiver
$cmd = 'exec '.__DIR__.'/../../receive '.__DIR__.'/../../oma.ini';

journalctl_catch($cmd, 'journal', '-u victron-ble _TRANSPORT=stdout', function($data, $ts) {
    switch (@$data['_SYSTEMD_UNIT']) {
    case 'victron-ble.service':
        // victron-ble outputs its data line-by-line as JSON
        $msg = json_decode($data['MESSAGE'], true);
        if ($msg === null) {
            throw new SkipMessage('Victron non-JSON data');
        }

        // Strip constant data
        unset($msg['address']);
        unset($msg['payload']['model_name']);
        unset($msg['payload']['aux_mode']);

        // Store
        return ['victron', $ts, json_encode($msg)];
    }
});
