#!/usr/bin/env php
<?php

require(__DIR__."/../common.php");

print("journal\n");
$cursor = fgets(STDIN);
if ($cursor === false) q("No remote cursor received");
$cursor=trim($cursor);

$cur = journalctl(STDOUT, '-u victron-ble _TRANSPORT=stdout', $cursor, function($data) {
    $ts = bcdiv($data['__REALTIME_TIMESTAMP'], 1000000, 3);
    if ($data['_SYSTEMD_UNIT'] == 'victron-ble.service') {
        $json = json_decode($data['MESSAGE'], true);
        if ($json === null) {
            fprintf(STDERR, 'Skipping Victron non-JSON data');
            return;
        }
        return ['victron_ble', $ts, $data['MESSAGE']];
    }
});

function q($msg, $exit_code=1) {
    fprintf(STDERR, $msg . "\n");
    exit($exit_code);
}
