#!/usr/bin/env php
<?php

require(__DIR__."/../common.php");

journalctl_catch('exec ssh -CT grafana', 'journal', '-u victron-ble _TRANSPORT=stdout', function($data, $ts) {
    if (@$data['_SYSTEMD_UNIT'] == 'victron-ble.service') {
        $json = json_decode($data['MESSAGE'], true);
        if ($json === null) {
            throw new SkipMessage('Victron non-JSON data');
        }
        return ['victron-ble', $ts, $data['MESSAGE']];
    }
});

